Integrate receipts extraction into ETHWorker
santiment/san-chain-exporter pull request #201
Opened 2024-07-24 08:25 UTC by YordanPavlov

This PR integrates the receipts extraction into ETHWorker. To achieve this it does the following steps:
1. Break the Exporter class into its two main functions, KafkaStorage and ZookeeperState.
2. Support multiple KafkaStorage instances per running exporter, each mode of operation is associated with one KafkaStorage.
3. Integrate the ReceiptsWorker into the ETHWorker classes. The latter already extracts receipts, it just needs to format them in the proper format and fill the receipts output topic.

2024-07-24 08:29 UTC, YordanPavlov commented on src/blockchains/construct_worker.ts
> -      return new ReceiptsWorker(settings);
Separate worker is no longer needed. We would use the `ETHWorker` to extract receipts, we can do it like this:

> KAFKA_TOPIC='native_token_transfers:eth_transfers_test_topic,receipts:receipts_test_topic'

If we want to extract transfers and receipts at once. If for some reason we want to have only receipts deploy, we can do:

> KAFKA_TOPIC='receipts:receipts_test_topic'

2024-07-24 08:32 UTC, YordanPavlov commented on src/blockchains/erc20/erc20_worker.ts
> +  async init(storage: KafkaStorage | Map<string, KafkaStorage>) {
Workers receive information for which output Kafka topics need to be filled and produce the needed data.

2024-07-24 08:35 UTC, YordanPavlov commented on src/blockchains/eth/eth_worker.ts
> +  async fetchData(fromBlock: number, toBlock: number): Promise<[Trace[], Map<number, ETHBlock>, ETHReceipt[]]> {
We fetch raw data depending on what outputs are needed. Some basic raw data like block times is needed for any output.

2024-07-25 14:33 UTC, WonderBeat requested changes

2025-04-25 06:26 UTC, closed without merging